// internshipsData.jsx

const internshipsData = [
  {
    id: 1,
    company: "Bonilla Group",
    description:
      "As a Machine Learning Intern, you will work on projects involving Testing, Project Planning, Smart Contracts. You will engage in practical assignments, collaborate with mentors and peers, and gain exposure to solving real-world challenges in these domains. This internship aims to build your expertise as a Machine Learning, while broadening your knowledge across multiple related areas.",
    duration: "1 Month",
    jobRole: "Machine Learning",
    jobTitle: "Machine Learning Intern",
    jobTopic: "Testing, Project Planning, Smart Contracts",
    jobType: "Onsite",
    lastDate: "11-11-2025",
    stipend: "10000/month",
    type: "Short Term",
  },
  {
    id: 2,
    company: "Shea-Thomas",
    description:
      "As a Machine Learning Intern, you will work on projects involving UI Prototyping, Social Media Marketing, Natural Language Processing...",
    duration: "2 Months",
    jobRole: "Machine Learning",
    jobTitle: "Machine Learning Intern",
    jobTopic:
      "UI Prototyping, Social Media Marketing, Natural Language Processing",
    jobType: "Remote",
    lastDate: "29-10-2025",
    stipend: "10000/month",
    type: "Short Term",
  },
  {
    id: 3,
    company: "Green, Guzman and Scott",
    description:
      "As a Machine Learning Intern, you will work on projects involving Risk Management, Testing, Copywriting...",
    duration: "1 Month",
    jobRole: "Machine Learning",
    jobTitle: "Machine Learning Intern",
    jobTopic: "Risk Management, Testing, Copywriting",
    jobType: "Onsite",
    lastDate: "09-11-2025",
    stipend: "5000/month",
    type: "Short Term",
  },
  {
    id: 4,
    company: "Barnes, Bell and Rivera",
    description:
      "As an AI Ethics Intern, you will work on projects involving Machine Learning, Natural Language Processing, SEM...",
    duration: "3 Months",
    jobRole: "AI Ethics",
    jobTitle: "AI Ethics Intern",
    jobTopic: "Machine Learning, Natural Language Processing, SEM",
    jobType: "Hybrid",
    lastDate: "10-11-2025",
    stipend: "2000/month",
    type: "Short Term",
  },
  {
    id: 5,
    company: "Cox-Rice",
    description:
      "As a Web Development Intern, you will work on projects involving Testing, Data Analysis, Risk Management...",
    duration: "6 Months",
    jobRole: "Web Development",
    jobTitle: "Web Development Intern",
    jobTopic: "Testing, Data Analysis, Risk Management",
    jobType: "Remote",
    lastDate: "12-10-2025",
    stipend: "0",
    type: "Long Term",
  },
  {
    id: 6,
    company: "Buchanan, Miranda and Ruiz",
    description:
      "As a Web Development Intern, you will work on projects involving Financial Modelling, UI Prototyping, Cloud Computing...",
    duration: "3 Months",
    jobRole: "Web Development",
    jobTitle: "Web Development Intern",
    jobTopic: "Financial Modelling, UI Prototyping, Cloud Computing",
    jobType: "Onsite",
    lastDate: "29-11-2025",
    stipend: "3000/month",
    type: "Long Term",
  },
  {
    id: 7,
    company: "Jones, Allen and Hernandez",
    description:
      "As a Data Science Intern, you will work on projects involving Wireframing, Risk Management, UI Prototyping...",
    duration: "2 Months",
    jobRole: "Data Science",
    jobTitle: "Data Science Intern",
    jobTopic: "Wireframing, Risk Management, UI Prototyping",
    jobType: "Onsite",
    lastDate: "27-10-2025",
    stipend: "4000/month",
    type: "Long Term",
  },
  {
    id: 8,
    company: "Bolton-Crawford",
    description:
      "As a Data Engineering Intern, you will work on projects involving Big Data, SEM, Deep Learning...",
    duration: "2 Months",
    jobRole: "Data Engineering",
    jobTitle: "Data Engineering Intern",
    jobTopic: "Big Data, SEM, Deep Learning",
    jobType: "Remote",
    lastDate: "02-10-2025",
    stipend: "4000/month",
    type: "Short Term",
  },
  {
    id: 9,
    company: "Hunt PLC",
    description:
      "As a Customer Success Intern, you will work on projects involving Machine Learning, Network Security, Customer Engagement...",
    duration: "3 Months",
    jobRole: "Customer Success",
    jobTitle: "Customer Success Intern",
    jobTopic: "Machine Learning, Network Security, Customer Engagement",
    jobType: "Remote",
    lastDate: "28-10-2025",
    stipend: "10000/month",
    type: "Short Term",
  },
  {
    id: 10,
    company: "Davis Group",
    description:
      "As a Data Science Intern, you will work on projects involving UI Prototyping, Scrum, AWS...",
    duration: "3 Months",
    jobRole: "Data Science",
    jobTitle: "Data Science Intern",
    jobTopic: "UI Prototyping, Scrum, AWS",
    jobType: "Hybrid",
    lastDate: "24-11-2025",
    stipend: "4000/month",
    type: "Long Term",
  },
];

export default internshipsData;
